### ISSUE TITLE
Make handler optional?

### ISSUE THREAD

**Issue by DeRain** [GeniusesOfSymfony/PubSubRouterBundle#12]
Hi guys, the package is amazing! I'm currently using it for route MQTT topics and it's helped to save a lot of time.

In my case i don't need to define callback at all - I just need the ability to generate routes from defined YML rules.

Don't you think about making the handler param optional? For now, i should define an empty handler in every route. 

For example:
```yaml
user_order_notification:
    channel: order/status/{order_id}/user/{user_id}
    handler: #required for now
    requirements:
        order_id:
          pattern: "d+"
        user_id:
          pattern: "d+"
```

Thanks!
